version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      # You can adjust environment variables as needed
      - FLASK_ENV=development
    volumes:
      # Mount the entire project directory
      - /Users/onelividusika/Desktop/Server Side/CW1/database.db:/app/database.db

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
